<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('competency_interviews', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('employer_id')->unsigned();
            $table->bigInteger('job_title_id')->unsigned();
            $table->bigInteger('interview_number')->unsigned()->comment('generated by the system');
            $table->bigInteger('cost_center_id')->unsigned();
            $table->bigInteger('cost_number')->unsigned();
            $table->date('date');
            $table->string('candidate_name');
            $table->string('firstname');
            $table->string('middlename')->nullable();
            $table->string('lastname');
            $table->integer('interviewer');
            $table->boolean('military_service')->comment('1 -Completed, 2- Didnt Attend');
            $table->integer('military_number')->nullable();
            $table->string('place_recruitment');
            $table->integer('year_experience');
            $table->integer('ranking_creterial_id')->nullable();
            $table->integer('education_knowledge')->comment('Educational qualification & professional related knowledge');
            $table->integer('relevant_experience')->comment('Quality & skills gained from past experience');
            $table->integer('major_achievement')->comment('The candidate major previous achivements related to the position requirement');
            $table->integer('language_fluency_id')->unsigned()->comment('The candidate ability to express him self in english');
            $table->integer('core_competence_id');
            $table->text('core_remark')->nullable();
            $table->integer('functional_competence_id');
            $table->text('functional_remark')->nullable();
            $table->integer('mgt_senior_competence_id')->comment('Managerial competencies/ Mid Senior Mngt Level');
            $table->text('mgt_senior_remark')->nullable();
            $table->integer('mgt_top_competence_id')->comment('Managerial competencies/ Top Mngt Level');
            $table->text('mgt_top_remark')->nullable();
            $table->integer('overall_rating');
            $table->text('main_strength')->nullable();
            $table->text('main_weakness')->nullable();
            $table->string('birth_place');
            $table->string('residence_place')->nullable();
            $table->boolean('relative_inside')->comment('1 - yes, 2- No');
            $table->string('relative_name')->nullable();
            $table->boolean('chronic_disease');
            $table->text('chronic_remarks')->nullable();
            $table->boolean('pregnant')->default('0')->comment('if 0 - N0, else Yes');
            $table->integer('pregnancy_months')->nullable();
            $table->boolean('employed_before')->comment('1 - yes, 2- No');
            $table->boolean('reference_check')->comment('1 - yes, 2- No');
            $table->text('reference_remarks')->nullable();
            $table->float('current_packages')->nullable();
            $table->float('agreed_salary');
            $table->string('required_notes')->nullable();
            $table->string('current_employed_entity')->nullable()->comment('1 - Private sector, 2- Public Sector');
            $table->boolean('social_insuarance_status')->comment('1 - yes, 2- No');
            $table->boolean('work_site')->comment('1 - yes, 2- No');
            $table->boolean('reallocation_place')->comment('1 - yes, 2- No');
            $table->boolean('recruiter_recommendations')->comment('1 - Accepted, 2- Not Accepted, 3 - Waiting List');
            $table->integer('recommended_title')->comment('Recommended job title');
            $table->boolean('downloaded')->nullable()->comment('1 - yes, 2- No');
            $table->boolean('uploaded')->nullable()->comment('1 - yes, 2- No');
            $table->date('uploaded_date')->nullable();
            $table->integer('status')->comment('0 - submitted, 1 - initiated, 2 - pending, 3 - Approved, 4 - rejected');
            $table->timestamps();
            $table->softDeletes();
            $table->foreign('job_title_id')->references('id')->on('job_title')->onUpdate('CASCADE')->onDelete('RESTRICT');
            $table->foreign('employer_id')->references('id')->on('employers')->onUpdate('CASCADE')->onDelete('RESTRICT');
            $table->foreign('cost_center_id')->references('id')->on('cost_centers')->onUpdate('CASCADE')->onDelete('RESTRICT');

        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('compentency_interviews');
    }
};
