<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('technical_interviews', function (Blueprint $table) {
            $table->increments('id');
            $table->bigInteger('job_title_id')->unsigned();
            $table->bigInteger('interview_number')->unsigned()->comment('generated by the system');
            $table->bigInteger('cost_center_id')->unsigned();
            $table->bigInteger('cost_number')->unsigned();
            $table->date('date');
            $table->string('candidate_name');
            $table->string('firstname');
            $table->string('middlename')->nullable();
            $table->string('lastname');
            $table->integer('interviewer')->comment('its id for auth user');
            $table->integer('ranking_creterial_id')->nullable();
            $table->integer('technical_skill')->comment('Educational qualification & professional related knowledge');
            $table->text('skill_remark')->nullable();
            $table->integer('relevant_experience')->comment('Quality & skills gained from past experience');
            $table->text('experience_remark')->nullable();
            $table->integer('knowledge_equipment')->comment('The candidate knowledge of tool or equipment related to the position requirement');
            $table->text('equipment_remark')->nullable();
            $table->integer('quality_awareness')->comment('Quality $ Safety awareness');
            $table->text('awareness_remark')->nullable();
             $table->integer('physical_capability')->comment('Quality $ Safety awareness');
            $table->text('capability_remark')->nullable();
            $table->integer('practical_test_id')->unsigned();
            $table->integer('overall_rating')->unsigned()->comment('This is accoring to ranking creterial');
            $table->boolean('final_recommendation')->comment('1 - Accepted, 2- Not Accepted');
            $table->integer('recommended_title')->comment('Recommended job title');
             $table->boolean('downloaded')->nullable()->comment('1 - yes, 2- No');
            $table->boolean('uploaded')->nullable()->comment('1 - yes, 2- No');
            $table->date('uploaded_date')->nullable();
            $table->integer('status')->comment('0 - submitted, 1 - initiated, 2 - pending, 3 - Approved, 4 - rejected');
            $table->timestamps();
            $table->softDeletes();
            $table->integer('employer_id')->unsigned()->nullable();
            $table->foreign('job_title_id')->references('id')->on('job_title')->onUpdate('CASCADE')->onDelete('RESTRICT');
            $table->foreign('employer_id')->references('id')->on('employers')->onUpdate('CASCADE')->onDelete('RESTRICT');
            $table->foreign('cost_center_id')->references('id')->on('cost_centers')->onUpdate('CASCADE')->onDelete('RESTRICT');
            $table->foreign('ranking_creterial_id')->references('id')->on('ranking_creterials')->onUpdate('CASCADE')->onDelete('RESTRICT');
            $table->foreign('practical_test_id')->references('id')->on('practical_tests')->onUpdate('CASCADE')->onDelete('RESTRICT');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('technical_interviews');
    }
};
