<?php

namespace Database\Seeders\Version100;

use Database\TruncateTable;
use Illuminate\Database\Seeder;
use Database\DisableForeignKeys;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{

    use DisableForeignKeys, TruncateTable;
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        // $this->disableForeignKeys("countries");
        // $this->delete('countries');

        $data = array(
            0 => array(
                'id' => 1,
                'name' => 'Tanzania',
                'code' => 'TZ',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Tanzanian',
            ),
            1 => array(
                'id' => 2,
                'name' => 'Andorra',
                'code' => 'AD',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Andorran',
            ),
            2 => array(
                'id' => 3,
                'name' => 'United Arab Emirates',
                'code' => 'AE',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'United Arab Emirates',
            ),
            3 => array(
                'id' => 4,
                'name' => 'Afghanistan',
                'code' => 'AF',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Afghanistan',
            ),
            4 => array(
                'id' => 5,
                'name' => 'Antigua and Barbuda',
                'code' => 'AG',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Antigua and Barbuda',
            ),
            5 => array(
                'id' => 6,
                'name' => 'Anguilla',
                'code' => 'AI',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Anguillan',
            ),
            6 => array(
                'id' => 7,
                'name' => 'Albania',
                'code' => 'AL',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Albanian',
            ),
            7 => array(
                'id' => 8,
                'name' => 'Armenia',
                'code' => 'AM',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Armenian',
            ),
            8 => array(
                'id' => 9,
                'name' => 'Angola',
                'code' => 'AO',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Angola',
            ),
            9 => array(
                'id' => 10,
                'name' => 'Antarctica',
                'code' => 'AQ',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Antarctica',
            ),
            10 => array(
                'id' => 11,
                'name' => 'Argentina',
                'code' => 'AR',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Argentinan',
            ),
            11 => array(
                'id' => 12,
                'name' => 'American Samoa',
                'code' => 'AS',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'American Samoa',
            ),
            12 => array(
                'id' => 13,
                'name' => 'Austria',
                'code' => 'AT',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Austria',
            ),
            13 => array(
                'id' => 14,
                'name' => 'Australia',
                'code' => 'AU',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Australia',
            ),
            14 => array(
                'id' => 15,
                'name' => 'Aruba',
                'code' => 'AW',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Aruba',
            ),
            15 => array(
                'id' => 16,
                'name' => 'Åland Islands',
                'code' => 'AX',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Åland Islands',
            ),
            16 => array(
                'id' => 17,
                'name' => 'Azerbaijan',
                'code' => 'AZ',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Azerbaijan',
            ),
            17 => array(
                'id' => 18,
                'name' => 'Bosnia and Herzegovina',
                'code' => 'BA',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Bosnia and Herzegovina',
            ),
            18 => array(
                'id' => 19,
                'name' => 'Barbados',
                'code' => 'BB',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Barbados',
            ),
            19 => array(
                'id' => 20,
                'name' => 'Bangladesh',
                'code' => 'BD',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Bangladesh',
            ),
            20 => array(
                'id' => 21,
                'name' => 'Belgium',
                'code' => 'BE',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Belgium',
            ),
            21 => array(
                'id' => 22,
                'name' => 'Burkina Faso',
                'code' => 'BF',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Burkina Faso',
            ),
            22 => array(
                'id' => 23,
                'name' => 'Bulgaria',
                'code' => 'BG',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Bulgaria',
            ),
            23 => array(
                'id' => 24,
                'name' => 'Bahrain',
                'code' => 'BH',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Bahrain',
            ),
            24 => array(
                'id' => 25,
                'name' => 'Burundi',
                'code' => 'BI',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Burundi',
            ),
            25 => array(
                'id' => 26,
                'name' => 'Benin',
                'code' => 'BJ',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Benin',
            ),
            26 => array(
                'id' => 27,
                'name' => 'Saint Barthélemy',
                'code' => 'BL',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Saint Barthélemy',
            ),
            27 => array(
                'id' => 28,
                'name' => 'Bermuda',
                'code' => 'BM',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Bermuda',
            ),
            28 => array(
                'id' => 29,
                'name' => 'Brunei Darussalam',
                'code' => 'BN',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Brunei Darussalam',
            ),
            29 => array(
                'id' => 30,
                'name' => 'Bolivia',
                'code' => 'BO',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Bolivia',
            ),
            30 => array(
                'id' => 31,
                'name' => 'Caribbean Netherlands',
                'code' => 'BQ',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Caribbean Netherlands',
            ),
            31 => array(
                'id' => 32,
                'name' => 'Brazil',
                'code' => 'BR',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Brazilian',
            ),
            32 => array(
                'id' => 33,
                'name' => 'Bahamas',
                'code' => 'BS',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Bahamas',
            ),
            33 => array(
                'id' => 34,
                'name' => 'Bhutan',
                'code' => 'BT',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Bhutan',
            ),
            34 => array(
                'id' => 35,
                'name' => 'Bouvet Island',
                'code' => 'BV',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Bouvet Island',
            ),
            35 => array(
                'id' => 36,
                'name' => 'Botswana',
                'code' => 'BW',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Botswana',
            ),
            36 => array(
                'id' => 37,
                'name' => 'Belarus',
                'code' => 'BY',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Belarus',
            ),
            37 => array(
                'id' => 38,
                'name' => 'Belize',
                'code' => 'BZ',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Belize',
            ),
            38 => array(
                'id' => 39,
                'name' => 'Canada',
                'code' => 'CA',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Canada',
            ),
            39 => array(
                'id' => 40,
                'name' => 'Cocos (Keeling) Islands',
                'code' => 'CC',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Cocos (Keeling) Islands',
            ),
            40 => array(
                'id' => 41,
                'name' => 'Congo, Democratic Republic of',
                'code' => 'CD',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Congo, Democratic Republic of',
            ),
            41 => array(
                'id' => 42,
                'name' => 'Central African Republic',
                'code' => 'CF',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Central African Republic',
            ),
            42 => array(
                'id' => 43,
                'name' => 'Congo',
                'code' => 'CG',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Congo',
            ),
            43 => array(
                'id' => 44,
                'name' => 'Switzerland',
                'code' => 'CH',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Switzerland',
            ),
            44 => array(
                'id' => 45,
                'name' => 'Côte d\'Ivoire',
                'code' => 'CI',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Côte d\'Ivoire',
            ),
            45 => array(
                'id' => 46,
                'name' => 'Cook Islands',
                'code' => 'CK',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Cook Islands',
            ),
            46 => array(
                'id' => 47,
                'name' => 'Chile',
                'code' => 'CL',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Chile',
            ),
            47 => array(
                'id' => 48,
                'name' => 'Cameroon',
                'code' => 'CM',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Cameroon',
            ),
            48 => array(
                'id' => 49,
                'name' => 'China',
                'code' => 'CN',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'China',
            ),
            49 => array(
                'id' => 50,
                'name' => 'Colombia',
                'code' => 'CO',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Colombian',
            ),
            50 => array(
                'id' => 51,
                'name' => 'Costa Rica',
                'code' => 'CR',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Costa Rica',
            ),
            51 => array(
                'id' => 52,
                'name' => 'Cuba',
                'code' => 'CU',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Cuba',
            ),
            52 => array(
                'id' => 53,
                'name' => 'Cape Verde',
                'code' => 'CV',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Cape Verde',
            ),
            53 => array(
                'id' => 54,
                'name' => 'Curaçao',
                'code' => 'CW',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Curaçao',
            ),
            54 => array(
                'id' => 55,
                'name' => 'Christmas Island',
                'code' => 'CX',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Christmas Island',
            ),
            55 => array(
                'id' => 56,
                'name' => 'Cyprus',
                'code' => 'CY',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Cyprus',
            ),
            56 => array(
                'id' => 57,
                'name' => 'Czech Republic',
                'code' => 'CZ',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Czech Republic',
            ),
            57 => array(
                'id' => 58,
                'name' => 'Germany',
                'code' => 'DE',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Germany',
            ),
            58 => array(
                'id' => 59,
                'name' => 'Djibouti',
                'code' => 'DJ',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Djibouti',
            ),
            59 => array(
                'id' => 60,
                'name' => 'Denmark',
                'code' => 'DK',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Denmark',
            ),
            60 => array(
                'id' => 61,
                'name' => 'Dominica',
                'code' => 'DM',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Dominica',
            ),
            61 => array(
                'id' => 62,
                'name' => 'Dominican Republic',
                'code' => 'DO',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Dominican Republic',
            ),
            62 => array(
                'id' => 63,
                'name' => 'Algeria',
                'code' => 'DZ',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Algeria',
            ),
            63 => array(
                'id' => 64,
                'name' => 'Ecuador',
                'code' => 'EC',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Ecuador',
            ),
            64 => array(
                'id' => 65,
                'name' => 'Estonia',
                'code' => 'EE',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Estonia',
            ),
            65 => array(
                'id' => 66,
                'name' => 'Egypt',
                'code' => 'EG',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Egypt',
            ),
            66 => array(
                'id' => 67,
                'name' => 'Western Sahara',
                'code' => 'EH',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Western Sahara',
            ),
            67 => array(
                'id' => 68,
                'name' => 'Eritrea',
                'code' => 'ER',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Eritrea',
            ),
            68 => array(
                'id' => 69,
                'name' => 'Spain',
                'code' => 'ES',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Spain',
            ),
            69 => array(
                'id' => 70,
                'name' => 'Ethiopia',
                'code' => 'ET',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Ethiopian',
            ),
            70 => array(
                'id' => 71,
                'name' => 'Finland',
                'code' => 'FI',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'Fin',
            ),
            71 => array(
                'id' => 72,
                'name' => 'Fiji',
                'code' => 'FJ',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            72 => array(
                'id' => 73,
                'name' => 'Falkland Islands',
                'code' => 'FK',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            73 => array(
                'id' => 74,
                'name' => 'Micronesia, Federated States of',
                'code' => 'FM',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            74 => array(
                'id' => 75,
                'name' => 'Faroe Islands',
                'code' => 'FO',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            75 => array(
                'id' => 76,
                'name' => 'France',
                'code' => 'FR',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            76 => array(
                'id' => 77,
                'name' => 'Gabon',
                'code' => 'GA',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            77 => array(
                'id' => 78,
                'name' => 'United Kingdom',
                'code' => 'GB',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            78 => array(
                'id' => 79,
                'name' => 'Grenada',
                'code' => 'GD',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            79 => array(
                'id' => 80,
                'name' => 'Georgia',
                'code' => 'GE',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            80 => array(
                'id' => 81,
                'name' => 'French Guiana',
                'code' => 'GF',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            81 => array(
                'id' => 82,
                'name' => 'Guernsey',
                'code' => 'GG',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            82 => array(
                'id' => 83,
                'name' => 'Ghana',
                'code' => 'GH',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            83 => array(
                'id' => 84,
                'name' => 'Gibraltar',
                'code' => 'GI',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            84 => array(
                'id' => 85,
                'name' => 'Greenland',
                'code' => 'GL',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            85 => array(
                'id' => 86,
                'name' => 'Gambia',
                'code' => 'GM',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            86 => array(
                'id' => 87,
                'name' => 'Guinea',
                'code' => 'GN',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            87 => array(
                'id' => 88,
                'name' => 'Guadeloupe',
                'code' => 'GP',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            88 => array(
                'id' => 89,
                'name' => 'Equatorial Guinea',
                'code' => 'GQ',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            89 => array(
                'id' => 90,
                'name' => 'Greece',
                'code' => 'GR',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            90 => array(
                'id' => 91,
                'name' => 'South Georgia and the South Sandwich Islands',
                'code' => 'GS',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            91 => array(
                'id' => 92,
                'name' => 'Guatemala',
                'code' => 'GT',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            92 => array(
                'id' => 93,
                'name' => 'Guam',
                'code' => 'GU',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            93 => array(
                'id' => 94,
                'name' => 'Guinea-Bissau',
                'code' => 'GW',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            94 => array(
                'id' => 95,
                'name' => 'Guyana',
                'code' => 'GY',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            95 => array(
                'id' => 96,
                'name' => 'Hong Kong',
                'code' => 'HK',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            96 => array(
                'id' => 97,
                'name' => 'Heard and McDonald Islands',
                'code' => 'HM',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            97 => array(
                'id' => 98,
                'name' => 'Honduras',
                'code' => 'HN',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            98 => array(
                'id' => 99,
                'name' => 'Croatia',
                'code' => 'HR',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            99 => array(
                'id' => 100,
                'name' => 'Haiti',
                'code' => 'HT',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            100 => array(
                'id' => 101,
                'name' => 'Hungary',
                'code' => 'HU',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            101 => array(
                'id' => 102,
                'name' => 'Indonesia',
                'code' => 'ID',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            102 => array(
                'id' => 103,
                'name' => 'Ireland',
                'code' => 'IE',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            103 => array(
                'id' => 104,
                'name' => 'Israel',
                'code' => 'IL',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            104 => array(
                'id' => 105,
                'name' => 'Isle of Man',
                'code' => 'IM',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            105 => array(
                'id' => 106,
                'name' => 'India',
                'code' => 'IN',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            106 => array(
                'id' => 107,
                'name' => 'British Indian Ocean Territory',
                'code' => 'IO',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            107 => array(
                'id' => 108,
                'name' => 'Iraq',
                'code' => 'IQ',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            108 => array(
                'id' => 109,
                'name' => 'Iran',
                'code' => 'IR',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            109 => array(
                'id' => 110,
                'name' => 'Iceland',
                'code' => 'IS',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            110 => array(
                'id' => 111,
                'name' => 'Italy',
                'code' => 'IT',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            111 => array(
                'id' => 112,
                'name' => 'Jersey',
                'code' => 'JE',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            112 => array(
                'id' => 113,
                'name' => 'Jamaica',
                'code' => 'JM',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            113 => array(
                'id' => 114,
                'name' => 'Jordan',
                'code' => 'JO',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            114 => array(
                'id' => 115,
                'name' => 'Japan',
                'code' => 'JP',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            115 => array(
                'id' => 116,
                'name' => 'Kenya',
                'code' => 'KE',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            116 => array(
                'id' => 117,
                'name' => 'Kyrgyzstan',
                'code' => 'KG',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            117 => array(
                'id' => 118,
                'name' => 'Cambodia',
                'code' => 'KH',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            118 => array(
                'id' => 119,
                'name' => 'Kiribati',
                'code' => 'KI',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            119 => array(
                'id' => 120,
                'name' => 'Comoros',
                'code' => 'KM',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            120 => array(
                'id' => 121,
                'name' => 'Saint Kitts and Nevis',
                'code' => 'KN',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            121 => array(
                'id' => 122,
                'name' => 'North Korea',
                'code' => 'KP',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            122 => array(
                'id' => 123,
                'name' => 'South Korea',
                'code' => 'KR',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            123 => array(
                'id' => 124,
                'name' => 'Kuwait',
                'code' => 'KW',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            124 => array(
                'id' => 125,
                'name' => 'Cayman Islands',
                'code' => 'KY',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            125 => array(
                'id' => 126,
                'name' => 'Kazakhstan',
                'code' => 'KZ',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            126 => array(
                'id' => 127,
                'name' => 'Lao People\'s Democratic Republic',
                'code' => 'LA',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            127 => array(
                'id' => 128,
                'name' => 'Lebanon',
                'code' => 'LB',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            128 => array(
                'id' => 129,
                'name' => 'Saint Lucia',
                'code' => 'LC',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            129 => array(
                'id' => 130,
                'name' => 'Liechtenstein',
                'code' => 'LI',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            130 => array(
                'id' => 131,
                'name' => 'Sri Lanka',
                'code' => 'LK',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            131 => array(
                'id' => 132,
                'name' => 'Liberia',
                'code' => 'LR',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            132 => array(
                'id' => 133,
                'name' => 'Lesotho',
                'code' => 'LS',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            133 => array(
                'id' => 134,
                'name' => 'Lithuania',
                'code' => 'LT',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            134 => array(
                'id' => 135,
                'name' => 'Luxembourg',
                'code' => 'LU',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            135 => array(
                'id' => 136,
                'name' => 'Latvia',
                'code' => 'LV',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            136 => array(
                'id' => 137,
                'name' => 'Libya',
                'code' => 'LY',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            137 => array(
                'id' => 138,
                'name' => 'Morocco',
                'code' => 'MA',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            138 => array(
                'id' => 139,
                'name' => 'Monaco',
                'code' => 'MC',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            139 => array(
                'id' => 140,
                'name' => 'Moldova',
                'code' => 'MD',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            140 => array(
                'id' => 141,
                'name' => 'Montenegro',
                'code' => 'ME',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            141 => array(
                'id' => 142,
                'name' => 'Saint-Martin (France)',
                'code' => 'MF',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            142 => array(
                'id' => 143,
                'name' => 'Madagascar',
                'code' => 'MG',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            143 => array(
                'id' => 144,
                'name' => 'Marshall Islands',
                'code' => 'MH',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            144 => array(
                'id' => 145,
                'name' => 'Macedonia',
                'code' => 'MK',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            145 => array(
                'id' => 146,
                'name' => 'Mali',
                'code' => 'ML',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            146 => array(
                'id' => 147,
                'name' => 'Myanmar',
                'code' => 'MM',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            147 => array(
                'id' => 148,
                'name' => 'Mongolia',
                'code' => 'MN',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            148 => array(
                'id' => 149,
                'name' => 'Macau',
                'code' => 'MO',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            149 => array(
                'id' => 150,
                'name' => 'Northern Mariana Islands',
                'code' => 'MP',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            150 => array(
                'id' => 151,
                'name' => 'Martinique',
                'code' => 'MQ',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            151 => array(
                'id' => 152,
                'name' => 'Mauritania',
                'code' => 'MR',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            152 => array(
                'id' => 153,
                'name' => 'Montserrat',
                'code' => 'MS',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            153 => array(
                'id' => 154,
                'name' => 'Malta',
                'code' => 'MT',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            154 => array(
                'id' => 155,
                'name' => 'Mauritius',
                'code' => 'MU',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            155 => array(
                'id' => 156,
                'name' => 'Maldives',
                'code' => 'MV',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            156 => array(
                'id' => 157,
                'name' => 'Malawi',
                'code' => 'MW',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            157 => array(
                'id' => 158,
                'name' => 'Mexico',
                'code' => 'MX',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            158 => array(
                'id' => 159,
                'name' => 'Malaysia',
                'code' => 'MY',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            159 => array(
                'id' => 160,
                'name' => 'Mozambique',
                'code' => 'MZ',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            160 => array(
                'id' => 161,
                'name' => 'Namibia',
                'code' => 'NA',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            161 => array(
                'id' => 162,
                'name' => 'New Caledonia',
                'code' => 'NC',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            162 => array(
                'id' => 163,
                'name' => 'Niger',
                'code' => 'NE',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            163 => array(
                'id' => 164,
                'name' => 'Norfolk Island',
                'code' => 'NF',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            164 => array(
                'id' => 165,
                'name' => 'Nigeria',
                'code' => 'NG',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            165 => array(
                'id' => 166,
                'name' => 'Nicaragua',
                'code' => 'NI',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            166 => array(
                'id' => 167,
                'name' => 'The Netherlands',
                'code' => 'NL',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            167 => array(
                'id' => 168,
                'name' => 'Norway',
                'code' => 'NO',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            168 => array(
                'id' => 169,
                'name' => 'Nepal',
                'code' => 'NP',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            169 => array(
                'id' => 170,
                'name' => 'Nauru',
                'code' => 'NR',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            170 => array(
                'id' => 171,
                'name' => 'Niue',
                'code' => 'NU',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            171 => array(
                'id' => 172,
                'name' => 'New Zealand',
                'code' => 'NZ',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            172 => array(
                'id' => 173,
                'name' => 'Oman',
                'code' => 'OM',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            173 => array(
                'id' => 174,
                'name' => 'Panama',
                'code' => 'PA',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            174 => array(
                'id' => 175,
                'name' => 'Peru',
                'code' => 'PE',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            175 => array(
                'id' => 176,
                'name' => 'French Polynesia',
                'code' => 'PF',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            176 => array(
                'id' => 177,
                'name' => 'Papua New Guinea',
                'code' => 'PG',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            177 => array(
                'id' => 178,
                'name' => 'Philippines',
                'code' => 'PH',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            178 => array(
                'id' => 179,
                'name' => 'Pakistan',
                'code' => 'PK',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            179 => array(
                'id' => 180,
                'name' => 'Poland',
                'code' => 'PL',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            180 => array(
                'id' => 181,
                'name' => 'St. Pierre and Miquelon',
                'code' => 'PM',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            181 => array(
                'id' => 182,
                'name' => 'Pitcairn',
                'code' => 'PN',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            182 => array(
                'id' => 183,
                'name' => 'Puerto Rico',
                'code' => 'PR',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            183 => array(
                'id' => 184,
                'name' => 'Palestine, State of',
                'code' => 'PS',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            184 => array(
                'id' => 185,
                'name' => 'Portugal',
                'code' => 'PT',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            185 => array(
                'id' => 186,
                'name' => 'Palau',
                'code' => 'PW',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            186 => array(
                'id' => 187,
                'name' => 'Paraguay',
                'code' => 'PY',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            187 => array(
                'id' => 188,
                'name' => 'Qatar',
                'code' => 'QA',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            188 => array(
                'id' => 189,
                'name' => 'Réunion',
                'code' => 'RE',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            189 => array(
                'id' => 190,
                'name' => 'Romania',
                'code' => 'RO',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            190 => array(
                'id' => 191,
                'name' => 'Serbia',
                'code' => 'RS',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            191 => array(
                'id' => 192,
                'name' => 'Russian Federation',
                'code' => 'RU',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            192 => array(
                'id' => 193,
                'name' => 'Rwanda',
                'code' => 'RW',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            193 => array(
                'id' => 194,
                'name' => 'Saudi Arabia',
                'code' => 'SA',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            194 => array(
                'id' => 195,
                'name' => 'Solomon Islands',
                'code' => 'SB',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            195 => array(
                'id' => 196,
                'name' => 'Seychelles',
                'code' => 'SC',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            196 => array(
                'id' => 197,
                'name' => 'Sudan',
                'code' => 'SD',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            197 => array(
                'id' => 198,
                'name' => 'Sweden',
                'code' => 'SE',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            198 => array(
                'id' => 199,
                'name' => 'Singapore',
                'code' => 'SG',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            199 => array(
                'id' => 200,
                'name' => 'Saint Helena',
                'code' => 'SH',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            200 => array(
                'id' => 201,
                'name' => 'Slovenia',
                'code' => 'SI',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            201 => array(
                'id' => 202,
                'name' => 'Svalbard and Jan Mayen Islands',
                'code' => 'SJ',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            202 => array(
                'id' => 203,
                'name' => 'Slovakia',
                'code' => 'SK',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            203 => array(
                'id' => 204,
                'name' => 'Sierra Leone',
                'code' => 'SL',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            204 => array(
                'id' => 205,
                'name' => 'San Marino',
                'code' => 'SM',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            205 => array(
                'id' => 206,
                'name' => 'Senegal',
                'code' => 'SN',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            206 => array(
                'id' => 207,
                'name' => 'Somalia',
                'code' => 'SO',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            207 => array(
                'id' => 208,
                'name' => 'Suriname',
                'code' => 'SR',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            208 => array(
                'id' => 209,
                'name' => 'South Sudan',
                'code' => 'SS',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            209 => array(
                'id' => 210,
                'name' => 'Sao Tome and Principe',
                'code' => 'ST',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            210 => array(
                'id' => 211,
                'name' => 'El Salvador',
                'code' => 'SV',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            211 => array(
                'id' => 212,
                'name' => 'Sint Maarten (Dutch part)',
                'code' => 'SX',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            212 => array(
                'id' => 213,
                'name' => 'Syria',
                'code' => 'SY',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            213 => array(
                'id' => 214,
                'name' => 'Swaziland',
                'code' => 'SZ',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            214 => array(
                'id' => 215,
                'name' => 'Turks and Caicos Islands',
                'code' => 'TC',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            215 => array(
                'id' => 216,
                'name' => 'Chad',
                'code' => 'TD',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            216 => array(
                'id' => 217,
                'name' => 'French Southern Territories',
                'code' => 'TF',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            217 => array(
                'id' => 218,
                'name' => 'Togo',
                'code' => 'TG',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            218 => array(
                'id' => 219,
                'name' => 'Thailand',
                'code' => 'TH',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            219 => array(
                'id' => 220,
                'name' => 'Tajikistan',
                'code' => 'TJ',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            220 => array(
                'id' => 221,
                'name' => 'Tokelau',
                'code' => 'TK',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            221 => array(
                'id' => 222,
                'name' => 'Timor-Leste',
                'code' => 'TL',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            222 => array(
                'id' => 223,
                'name' => 'Turkmenistan',
                'code' => 'TM',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            223 => array(
                'id' => 224,
                'name' => 'Tunisia',
                'code' => 'TN',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            224 => array(
                'id' => 225,
                'name' => 'Tonga',
                'code' => 'TO',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            225 => array(
                'id' => 226,
                'name' => 'Turkey',
                'code' => 'TR',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            226 => array(
                'id' => 227,
                'name' => 'Trinidad and Tobago',
                'code' => 'TT',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            227 => array(
                'id' => 228,
                'name' => 'Tuvalu',
                'code' => 'TV',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            228 => array(
                'id' => 229,
                'name' => 'Taiwan',
                'code' => 'TW',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),

            229 => array(
                'id' => 230,
                'name' => 'Ukraine',
                'code' => 'UA',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            230 => array(
                'id' => 231,
                'name' => 'Uganda',
                'code' => 'UG',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            231 => array(
                'id' => 232,
                'name' => 'United States Minor Outlying Islands',
                'code' => 'UM',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            232 => array(
                'id' => 233,
                'name' => 'United States',
                'code' => 'US',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            233 => array(
                'id' => 234,
                'name' => 'Uruguay',
                'code' => 'UY',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            234 => array(
                'id' => 235,
                'name' => 'Uzbekistan',
                'code' => 'UZ',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            235 => array(
                'id' => 236,
                'name' => 'Vatican',
                'code' => 'VA',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            236 => array(
                'id' => 237,
                'name' => 'Saint Vincent and the Grenadines',
                'code' => 'VC',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            237 => array(
                'id' => 238,
                'name' => 'Venezuela',
                'code' => 'VE',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            238 => array(
                'id' => 239,
                'name' => 'Virgin Islands (British)',
                'code' => 'VG',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            239 => array(
                'id' => 240,
                'name' => 'Virgin Islands (U.S.)',
                'code' => 'VI',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            240 => array(
                'id' => 241,
                'name' => 'Vietnam',
                'code' => 'VN',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            241 => array(
                'id' => 242,
                'name' => 'Vanuatu',
                'code' => 'VU',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            242 => array(
                'id' => 243,
                'name' => 'Wallis and Futuna Islands',
                'code' => 'WF',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            243 => array(
                'id' => 244,
                'name' => 'Samoa',
                'code' => 'WS',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            244 => array(
                'id' => 245,
                'name' => 'Yemen',
                'code' => 'YE',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            245 => array(
                'id' => 246,
                'name' => 'Mayotte',
                'code' => 'YT',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            246 => array(
                'id' => 247,
                'name' => 'South Africa',
                'code' => 'ZA',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            247 => array(
                'id' => 248,
                'name' => 'Zambia',
                'code' => 'ZM',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
            248 => array(
                'id' => 249,
                'name' => 'Zimbabwe',
                'code' => 'ZW',
                'created_at' => '2024-01-09 14:33:47',
                'updated_at' => null,
                'deleted_at' => null,
                'description' => 'country_name',
            ),
        );


$lastRecordCount = $this->getRecordCount("countries");
        $slice = array_slice($data, $lastRecordCount);;
        if (count($slice)) {
            DB::table('countries')->insert($slice);
        }

    }
}
