<?php

namespace Database\Seeders\Version100;

use DB;
use Database\TruncateTable;
use Illuminate\Database\Seeder;
use Database\DisableForeignKeys;

class DocumentsTableSeeder extends Seeder
{

    use DisableForeignKeys, TruncateTable;
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        $this->disableForeignKeys('documents');
        $this->delete('documents');

        DB::table('documents')->insert(array(
            0 =>
            array(
                'id' => 1,
                'name' => 'Employee\'s policy',
                'document_group_id' => '1',
                'description' => NULL,
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-01-11 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
            1 =>
            array(
                'id' => 2,
                'name' => 'Guideline',
                'document_group_id' => '1',
                'description' => NULL,
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-01-11 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
            2 =>
            array(
                'id' => 3,
                'name' => 'Access Form',
                'document_group_id' => '1',
                'description' => NULL,
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-01-11 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
            3 =>
            array(
                'id' => 4,
                'name' => 'User Manual',
                'document_group_id' => '2',
                'description' => NULL,
                'isrecurring' => '0',
                'ismandatory' => '0',
                'isactive' => '1',
                'created_at' => '2024-01-11 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
            4 =>
            array(
                'id' => 5,
                'name' => 'Job Application Request',
                'document_group_id' => '3',
                'description' => 'job_request_doc',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-01-11 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
            5 =>
            array(
                'id' => 6,
                'name' => 'Shortlisted Candidate',
                'document_group_id' => '3',
                'description' => 'shortlisted_doc',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-01-11 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
            6 =>
            array(
                'id' => 7,
                'name' => 'Driving Licence',
                'document_group_id' => '4',
                'description' => 'driving_licence',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-01-11 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
            7 =>
            array(
                'id' => 8,
                'name' => 'Practical test',
                'document_group_id' => '4',
                'description' => 'practical_test_doc',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-01-11 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
            8 =>
            array(
                'id' => 9,
                'name' => 'Education Certificate',
                'document_group_id' => '5',
                'description' => NULL,
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-01-11 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
            9 =>
            array(
                'id' => 10,
                'name' => 'NHIF Certificate',
                'document_group_id' => '6',
                'description' => 'nhif_doc',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-01-11 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
            10 =>
            array(
                'id' => 11,
                'name' => 'Employer Tin',
                'document_group_id' => '6',
                'description' => 'tin_doc',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-01-11 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
            11 =>
            array(
                'id' => 12,
                'name' => 'NSSF certificate',
                'document_group_id' => '6',
                'description' => 'nssf_doc',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-01-11 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
            12 =>
            array(
                'id' => 13,
                'name' => 'WCF certificate',
                'document_group_id' => '6',
                'description' => 'wcf_doc',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-01-11 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
            13 =>
            array(
                'id' => 14,
                'name' => 'OSHA certificate',
                'document_group_id' => '6',
                'description' => 'osha_doc',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-01-11 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
            14 =>
            array(
                'id' => 15,
                'name' => 'Education Certificate',
                'document_group_id' => '7',
                'description' => 'education_cert',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-01-11 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
            15 =>
            array(
                'id' => 16,
                'name' => 'passport',
                'document_group_id' => '7',
                'description' => 'passport_doc',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-01-11 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
            16 =>
            array(
                'id' => 17,
                'name' => 'National Id (NIDA)',
                'document_group_id' => '7',
                'description' => 'nida_doc',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-01-11 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
 17 =>
            array(
                'id' => 18,
                'name' => 'Curricrumn vitae (CV)',
                'document_group_id' => '7',
                'description' => 'cv_doc',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-01-11 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
 18 =>
            array(
                'id' => 19,
                'name' => 'NSSF membership',
                'document_group_id' => '7',
                'description' => 'nssf_membership',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-01-11 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
 19 =>
            array(
                'id' => 20,
                'name' => 'Introduction Letter',
                'document_group_id' => '7',
                'description' => 'induction_doc',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-01-11 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
 20 =>
            array(
                'id' => 21,
                'name' => 'Two Guarantors Letter',
                'document_group_id' => '7',
                'description' => 'guarantors',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-01-11 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
 21 =>
            array(
                'id' => 22,
                'name' => 'Reference Letter',
                'document_group_id' => '7',
                'description' => 'referenc_doc',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-01-11 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
 22 =>
            array(
                'id' => 23,
                'name' => 'Certificate of Service',
                'document_group_id' => '7',
                'description' => 'certificate_service',
                'isrecurring' => '0',
                'ismandatory' => '0',
                'isactive' => '1',
                'created_at' => '2024-01-11 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
 23 =>
            array(
                'id' => 24,
                'name' => 'Police Clearance',
                'document_group_id' => '7',
                'description' => 'police_doc',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-01-11 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
 24 =>
            array(
                'id' => 25,
                'name' => 'Pre employement Osha Medical checkup',
                'document_group_id' => '7',
                'description' => 'osha_checkup',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-01-11 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
 25 =>
            array(
                'id' => 26,
                'name' => 'Social Record Signed ',
                'document_group_id' => '8',
                'description' => 'social_signed_doc',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-01-11 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
 26 =>
            array(
                'id' => 27,
                'name' => 'employee hr policy',
                'document_group_id' => '9',
                'description' => NULL,
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-01-11 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
         27 =>
            array(
                'id' => 28,
                'name' => 'Training form',
                'document_group_id' => '9',
                'description' => NULL,
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-01-11 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
            28 =>
            array(
                'id' => 29,
                'name' => 'vrn certificate',
                'document_group_id' => '6',
                'description' => NULL,
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-01-11 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
   29 =>
            array(
                'id' => 30,
                'name' => 'Military Attachment',
                'document_group_id' => '5',
                'description' => 'military_doc',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-01-11 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
  30 =>
            array(
                'id' => 31,
                'name' => 'Hr Signed Form',
                'document_group_id' => '5',
                'description' => 'hr_signed_doc',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-01-11 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
 31 =>
            array(
                'id' => 32,
                'name' => 'Technical Signed Document',
                'document_group_id' => '4',
                'description' => 'technical_signed_doc',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-01-11 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
     32 =>
            array(
                'id' => 33,
                'name' => 'Military Service attachment',
                'document_group_id' => '7',
                'description' => 'military_attach',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-02-27 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
     33 =>
            array(
                'id' => 34,
                'name' => 'Marriage Certificate',
                'document_group_id' => '7',
                'description' => 'marriage_cert',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-02-27 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
    34 =>
            array(
                'id' => 35,
                'name' => 'Referes Passport',
                'document_group_id' => '7',
                'description' => 'referee_passport',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-02-27 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
 35 =>
            array(
                'id' => 36,
                'name' => 'Signed Personal Detailed',
                'document_group_id' => '7',
                'description' => 'personal_signed_doc',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-02-27 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
 36 =>
            array(
                'id' => 37,
                'name' => 'Special Certificate Related',
                'document_group_id' => '7',
                'description' => 'special_cert_related',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-02-27 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
 37 =>
            array(
                'id' => 38,
                'name' => 'Combined Accademic Certificate',
                'document_group_id' => '7',
                'description' => 'combined_certificate',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-02-27 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
 38 =>
            array(
                'id' => 39,
                'name' => 'ID-Copy of ID',
                'document_group_id' => '7',
                'description' => 'id_copy',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-02-27 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
 39 =>
            array(
                'id' => 40,
                'name' => 'Bank Account Details or Verification Form',
                'document_group_id' => '7',
                'description' => 'bank_detail_doc',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-02-27 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
 40 =>

            array(
                'id' => 41,
                'name' => 'Osha Report',
                'document_group_id' => '8',
                'description' => 'osha_report_doc',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-03-06 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
 41 =>

            array(
                'id' => 42,
                'name' => 'Children Certificate',
                'document_group_id' => '8',
                'description' => 'children_certificate',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-03-06 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
42 =>

            array(
                'id' => 43,
                'name' => 'Job description attachment',
                'document_group_id' => '11',
                'description' => 'job_description_doc',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-03-12 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),
43 =>

            array(
                'id' => 44,
                'name' => 'Employee Contract Details',
                'document_group_id' => '11',
                'description' => 'contract_detail_signed',
                'isrecurring' => '0',
                'ismandatory' => '1',
                'isactive' => '1',
                'created_at' => '2024-03-12 08:18:07',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'anysource' => 1,
                'isother' => 0,
                'document_order' => NULL,
            ),


        ));


        $this->enableForeignKeys('documents');
    }
}
