<?php

namespace Database\Seeders\Version100;


use Database\TruncateTable;
use Illuminate\Database\Seeder;
use Database\DisableForeignKeys;
use Illuminate\Support\Facades\DB;

class UsersTableSeeder extends Seeder
{
    use DisableForeignKeys, TruncateTable;
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $data = array(
            //initial password:     welcome1
            0 =>
            array(
                'id' => '1',
                'username' => 'omsungu',
                'samaccountname' => 'ockline.msungu',
                'password' => '$2y$12$y90Xj/BW7Yg/s/ONTjKRb.GV23KrFeBbzAKJl47i085zgBBkLpNsO',
                'firstname' => 'Ockline',
                'lastname' => 'Msungu',
                'middlename' => 'M',
                'email' => 'ockline.msungu@econsult.co.tz',
                'phone' => '0762700692',
                'dob' => '2001-01-01',
                'employer_id' => 1,
                'department_id' => 1,
                'section_id' => 2,
                'designation_id' => 1,
                'gender_id' => 1,
                'email_verified_at' => null,
                'active' => 1,
                'available' => 1,
                'last_login' => NULL,
                'remember_token' => NULL,
                'created_by' => 1,
                'location_project' => NULL,
                'project_name' => null,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                // 'sub' => NULL,
                // 'user_sub_id'=>NULL,
            ),
            1 =>
            array(
                'id' => '2',
                'username' => 'smtalemwa',
                'samaccountname' => NULL,
                'password' => '$2y$12$y90Xj/BW7Yg/s/ONTjKRb.GV23KrFeBbzAKJl47i085zgBBkLpNsO',
                'firstname' => 'Samuel',
                'lastname' => 'Mtalwemwa',
                'middlename' => '',
                'email' => 'samuel@socrate.co.tz',
                'phone' => '0762700692',
                'dob' => '2001-01-01',
                'employer_id' => 1,
                'department_id' => 1,
                'section_id' => 2,
                'designation_id' => 1,
                'gender_id' => 1,
                'email_verified_at' => null,
                'active' => 1,
                'available' => 1,
                'last_login' => NULL,
                'remember_token' => NULL,
                'created_by' => 1,
                'location_project' => NULL,
                'project_name' => null,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                // 'sub' => NULL,
                // 'user_sub_id'=>NULL,
            ),
            2 =>
            array(
                'id' => '3',
                'username' => 'emtalemwa',
                'samaccountname' => NULL,
                'password' => '$2y$12$y90Xj/BW7Yg/s/ONTjKRb.GV23KrFeBbzAKJl47i085zgBBkLpNsO',
                'firstname' => 'Ellen',
                'lastname' => 'Mtalemwa',
                'middlename' => '',
                'email' => 'ellen@socrace.co.tz',
                'phone' => '0762700692',
                'dob' => '2001-01-01',
                'employer_id' => 1,
                'department_id' => 1,
                'section_id' => 2,
                'designation_id' => 1,
                'gender_id' => 1,
                'email_verified_at' => null,
                'active' => 1,
                'available' => 1,
                'last_login' => NULL,
                'remember_token' => NULL,
                'created_by' => 1,
                'location_project' => NULL,
                'project_name' => null,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                // 'sub' => NULL,
                // 'user_sub_id'=>NULL,
            ),
            3 =>
            array(
                'id' => '4',
                'username' => 'kKajolo',
                'samaccountname' => NULL,
                'password' => '$2y$12$y90Xj/BW7Yg/s/ONTjKRb.GV23KrFeBbzAKJl47i085zgBBkLpNsO',
                'firstname' => 'kheri',
                'lastname' => 'Kajolo',
                'middlename' => 'M',
                'email' => 'kherykajolo@socrate.co.tz',
                'phone' => '0762700692',
                'dob' => '2001-01-01',
                'employer_id' => 1,
                'department_id' => 1,
                'section_id' => 2,
                'designation_id' => 1,
                'gender_id' => 1,
                'email_verified_at' => null,
                'active' => 1,
                'available' => 1,
                'last_login' => NULL,
                'remember_token' => NULL,
                'created_by' => 1,
                'location_project' => NULL,
                'project_name' => null,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                // 'sub' => NULL,
                // 'user_sub_id'=>NULL,
            ),
             4 =>
            array(
                'id' => '5',
                'username' => 'KAssistant',
                'samaccountname' => NULL,
                'password' => '$2y$12$y90Xj/BW7Yg/s/ONTjKRb.GV23KrFeBbzAKJl47i085zgBBkLpNsO',
                'firstname' => 'Personal',
                'lastname' => 'Assistant',
                'middlename' => 'M',
                'email' => 'pa@socrate.co.tz',
                'phone' => '0762700692',
                'dob' => '2001-01-01',
                'employer_id' => 1,
                'department_id' => 1,
                'section_id' => 2,
                'designation_id' => 1,
                'gender_id' => 1,
                'email_verified_at' => null,
                'active' => 1,
                'available' => 1,
                'last_login' => NULL,
                'remember_token' => NULL,
                'created_by' => 1,
                'location_project' => NULL,
                'project_name' => null,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                // 'sub' => NULL,
                // 'user_sub_id'=>NULL,
            ),
             5 =>
            array(
                'id' => '6',
                'username' => 'MSayed  ',
                'samaccountname' => NULL,
                'password' => '$2y$12$y90Xj/BW7Yg/s/ONTjKRb.GV23KrFeBbzAKJl47i085zgBBkLpNsO',
                'firstname' => 'Mohamed',
                'lastname' => 'Sayed',
                'middlename' => 's',
                'email' => 'mohamedsayed@socrate.co.tz ',
                'phone' => '0762700692',
                'dob' => '2001-01-01',
                'employer_id' => 1,
                'department_id' => 1,
                'section_id' => 2,
                'designation_id' => 1,
                'gender_id' => 1,
                'email_verified_at' => null,
                'active' => 1,
                'available' => 1,
                'last_login' => NULL,
                'remember_token' => NULL,
                'created_by' => 1,
                'location_project' => NULL,
                'project_name' => null,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                // 'sub' => NULL,
                // 'user_sub_id'=>NULL,
            ),
  6 =>
            array(
                'id' => '7',
                'username' => 'TChacha',
                'samaccountname' => NULL,
                'password' => '$2y$12$y90Xj/BW7Yg/s/ONTjKRb.GV23KrFeBbzAKJl47i085zgBBkLpNsO',
                'firstname' => 'Tufikile',
                'lastname' => 'Chacha',
                'middlename' => 'Paul',
                'email' => 'tufikilepaul@socrate.co.tz',
                'phone' => '0762700692',
                'dob' => '2001-01-01',
                'employer_id' => 1,
                'department_id' => 1,
                'section_id' => 2,
                'designation_id' => 1,
                'gender_id' => 1,
                'email_verified_at' => null,
                'active' => 1,
                'available' => 1,
                'last_login' => NULL,
                'remember_token' => NULL,
                'created_by' => 1,
                'location_project' => NULL,
                'project_name' => null,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                // 'sub' => NULL,
                // 'user_sub_id'=>NULL,
            ),
  7 =>
            array(
                'id' => '8',
                'username' => 'WMsangi',
                'samaccountname' => NULL,
                'password' => '$2y$12$y90Xj/BW7Yg/s/ONTjKRb.GV23KrFeBbzAKJl47i085zgBBkLpNsO',
                'firstname' => 'Witness',
                'lastname' => 'Msangi',
                'middlename' => 'M',
                'email' => 'witnessmsangi@socrate.co.tz',
                'phone' => '0762700692',
                'dob' => '2001-01-01',
                'employer_id' => 1,
                'department_id' => 1,
                'section_id' => 2,
                'designation_id' => 1,
                'gender_id' => 1,
                'email_verified_at' => null,
                'active' => 1,
                'available' => 1,
                'last_login' => NULL,
                'remember_token' => NULL,
                'created_by' => 1,
                'location_project' => NULL,
                'project_name' => null,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                // 'sub' => NULL,
                // 'user_sub_id'=>NULL,
            ),
//   8 =>
//             array(
//                 'id' => '9',
//                 'username' => 'kKajolo',
//                 'samaccountname' => NULL,
//                 'password' => '$2y$12$y90Xj/BW7Yg/s/ONTjKRb.GV23KrFeBbzAKJl47i085zgBBkLpNsO',
//                 'firstname' => 'kheri',
//                 'lastname' => 'Kajolo',
//                 'middlename' => 'M',
//                 'email' => 'kheri.kajolo@econsult.co.tz',
//                 'phone' => '0762700692',
//                 'dob' => '2001-01-01',
//                 'employer_id' => 1,
//                 'department_id' => 1,
//                 'section_id' => 2,
//                 'designation_id' => 1,
//                 'gender_id' => 1,
//                 'email_verified_at' => null,
//                 'active' => 1,
//                 'available' => 1,
//                 'last_login' => NULL,
//                 'remember_token' => NULL,
//                 'created_by' => 1,
//                 'location_project' => NULL,
//                 'project_name' => null,
//                 'created_at' => NULL,
//                 'updated_at' => NULL,
//                 'deleted_at' => NULL,
//                 // 'sub' => NULL,
//                 // 'user_sub_id'=>NULL,
//             ),

        );

        $this->enableForeignKeys('users');

 $lastRecordCount = $this->getRecordCount("users");
        $slice = array_slice($data, $lastRecordCount);;
        if (count($slice)) {
            DB::table('users')->insert($slice);
        }
    }
}
